#### master ####
spring:
  profiles:
    active: @profile.active@
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    servlet:
      load-on-startup: 1
  jackson:
    default-property-inclusion: NON_NULL
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
server:
  servlet:
    encoding:
      force: true
    context-path: /olserv

---
#### dev ####
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/olserv_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
# 订阅模版
url-template:
  account-subscribe: http://127.0.0.1:8080/olserv/account/{accountId}/access-keys/subscribe

---
#### prod ####
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: olserv
    password: pwd@123
    url: jdbc:mysql://production-database/olserv?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
logging:
  file:
    name: /var/log/olserv.log

# 订阅模版
url-template:
  account-subscribe: http://interface.azhicloud.cn:9999/olserv/account/{accountId}/access-keys/subscribe