spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: olserv
    password: pwd@123
    url: jdbc:mysql://pi.wg/olserv?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  mvc:
    servlet:
      load-on-startup: 1
  jackson:
    default-property-inclusion: NON_NULL
  activemq:
    broker-url: tcp://101.34.23.55:61616
    in-memory: false
    packages:
      trust-all: false
  mail:
    host: smtp.qiye.aliyun.com
    port: 465
    protocol: smtps
    username: notifier@azhicloud.cn
    password: password123KBL
    from: notifier@azhicloud.cn
    # 是否生成主题编号（同主题的邮件会被分组）
    generate-subject-no: false
server:
  servlet:
    encoding:
      force: true
    context-path: /olserv
alarm:
  mail:
    receiver: carbule.bar@gmail.com
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  file:
    name: /var/log/olserv.log
template:
  subscribe-link: http://interface.azhicloud.cn:9999/olserv/account/{0}/access-keys/subscribe